---
blank_issues_enabled: false
contact_links:
  - name: Project MAPS Community Support
    url: https://github.com/kgreen1200/project-maps/discussions
    about: Please and answer general questions about the project here.
